from __future__ import annotations

from typing import List, Set


COMMON_WORDS: Set[str] = {
    "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will", "would", "could",
    "should", "may", "might", "shall", "can", "need", "dare", "ought",
    "used", "to", "of", "in", "for", "on", "with", "at", "by", "from",
    "as", "into", "through", "during", "before", "after", "above", "below",
    "between", "out", "off", "over", "under", "again", "further", "then",
    "once", "here", "there", "when", "where", "why", "how", "all", "both",
    "each", "few", "more", "most", "other", "some", "such", "no", "nor",
    "not", "only", "own", "same", "so", "than", "too", "very", "just",
    "because", "but", "and", "or", "if", "while", "this", "that", "these",
    "those", "i", "me", "my", "we", "our", "you", "your", "he", "him",
    "his", "she", "her", "it", "its", "they", "them", "their", "which",
    "what", "who", "whom", "whose", "about", "up", "down", "also", "been",
    "got", "get", "getting", "let", "like", "made", "now", "see", "way",
    "well", "back", "even", "still", "take", "come", "go", "know", "first",
    "last", "long", "great", "little", "old", "right", "big", "high",
    "small", "large", "next", "early", "young", "important", "however",
    "another", "upon", "often", "among", "whether", "within", "without",
    "three", "four", "five", "six", "seven", "eight", "nine", "ten",
    "given", "since", "part", "case", "time", "example", "section",
    "chapter", "respectively", "denote", "denotes", "note", "noted",
    "thus", "hence", "therefore", "furthermore", "moreover", "additionally",
    "specifically", "particularly", "generally", "typically", "usually",
    "simply", "already", "nearly", "almost", "rather", "quite", "instead",
    "either", "neither", "less", "every", "describe", "describes",
    "described", "consider", "considered", "obtain", "obtained", "achieve",
    "achieved", "provide", "provided", "represent", "represented",
    "correspond", "corresponding", "previous", "following", "left",
    "final", "main", "total", "full", "single", "possible", "available",
    "standard", "common", "specific", "certain", "similar", "various",
    "several", "additional", "separate", "entire", "special", "recent",
    "current", "original", "basic", "simple", "complex", "multiple",
    "direct", "indirect", "associated", "related", "combined", "respective",
    "effective", "efficient", "significant", "appropriate", "necessary",
    "sufficient", "potential", "practical", "traditional", "conventional",
    "alternative", "general", "natural", "global", "local", "abstract",
    "concrete", "linear", "continuous", "discrete", "random", "dynamic",
    "static", "positive", "negative", "zero", "infinite", "finite",
    "optimal", "maximum", "minimum", "average", "expected", "actual",
    "real", "virtual", "digital", "physical", "logical", "formal",
    "internal", "external", "overall", "partial", "complete", "equal",
    "equivalent", "identical", "unique", "constant", "variable", "fixed",
    "free", "open", "closed", "public", "private", "shared", "parallel",
    "sequential", "distributed", "centralized", "flat", "deep", "shallow",
    "wide", "narrow", "thick", "thin", "hard", "soft", "strong", "weak",
    "fast", "slow", "hot", "cold", "light", "dark", "black", "white",
    "true", "false", "correct", "incorrect", "valid", "invalid",
    "consistent", "inconsistent", "compatible", "proportional", "inversely",
    "directly", "approximately", "roughly", "precisely", "exactly",
    "essentially", "fundamentally", "primarily", "mainly", "largely",
    "partially", "completely", "entirely", "fully", "totally", "absolutely",
    "relatively", "comparatively", "consequently", "subsequently",
    "previously", "eventually", "ultimately", "initially", "originally",
    "secondarily", "central", "peripheral", "dominant", "superior",
    "inferior", "major", "minor", "key", "core", "outer", "inner",
    "upper", "lower", "higher", "greater", "lesser", "faster", "slower",
    "earlier", "later", "longer", "shorter", "wider", "broader", "deeper",
    "thicker", "heavier", "lighter", "larger", "smaller", "newer", "older",
    "richer", "poorer", "stronger", "weaker", "harder", "softer",
    "brighter", "darker", "closer", "further", "denser", "sparser",
    "thinner", "smoother", "rougher", "cleaner", "clearer", "vaguer",
    "simpler", "easier", "safer", "riskier", "cheaper", "rarer",
    "latter", "former", "model", "models", "output",
    "input", "two", "one", "new", "use", "used", "using", "set", "number",
    "table", "figure", "result", "results", "different", "based", "shown",
    "show", "type", "work", "make", "per", "much", "many", "best",
    "better", "good", "state", "data", "task", "tasks", "method", "methods",
    "approach", "problem", "process", "system", "level", "form",
    "effect", "value", "area", "rate", "change", "development",
    "research", "analysis", "study", "group", "effect", "order",
    "fact", "hand", "point", "world", "life", "year", "day",
    "thing", "man", "woman", "child", "government", "country",
}

NOISE_TERMS: Set[str] = {
    "http", "https", "url", "doi", "org", "arxiv", "abs", "pdf",
    "www", "com", "net", "edu", "vol", "pp", "isbn", "issn",
    "fig", "figure", "table", "appendix", "et", "al", "etal",
    "university", "institute", "department", "conference", "proceedings",
    "journal", "press", "pages", "ieee", "acm", "neurips", "icml",
    "iclr", "aaai", "acl", "emnlp", "naacl", "workshop", "symposium",
    "volume", "issue", "page", "submitted", "accepted", "published",
    "preprint", "manuscript", "draft", "bibtex", "citeseer",
    "pubmed", "scopus", "elsevier", "springer", "wiley", "oxford",
    "cambridge", "mit", "stanford", "harvard", "berkeley",
    "copyright", "license", "version", "draft", "revision",
}

TECHNICAL_SUFFIXES: List[str] = [
    "tion", "ment", "ness", "ity", "ism", "ive", "ory", "able", "ible",
    "ful", "ous", "ize", "ise", "ify", "ate", "ent", "ant", "ing",
    "net", "ary", "acy", "ics", "oid", "gram", "graph", "scope",
    "meter", "ology", "onomy", "pathy", "genic", "phile", "phobe",
    "form", "fold", "ward", "wise", "tion", "sion", "ance", "ence",
    "ling", "ment", "ship", "dom", "hood",
]

DOMAIN_STOPWORDS: Set[str] = {
    "according", "based", "using", "used", "show", "shown", "result",
    "results", "method", "methods", "approach", "proposed", "paper",
    "work", "study", "research", "analysis", "data", "set", "model",
    "figure", "table", "section", "chapter", "page", "equation",
    "algorithm", "problem", "solution", "example", "given", "note",
    "see", "also", "however", "therefore", "thus", "hence", "moreover",
    "furthermore", "additionally", "respectively", "particular",
    "specific", "general", "different", "similar", "important",
    "significant", "possible", "available", "standard", "common",
}